// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stratoapi.Data;

#nullable disable

namespace stratoapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106145120_UpdateSeedUserPassword")]
    partial class UpdateSeedUserPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("stratoapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seed@example.com",
                            PasswordHash = new byte[] { 217, 242, 131, 147, 14, 138, 55, 19, 236, 25, 116, 175, 118, 49, 101, 111, 69, 35, 217, 141, 2, 232, 4, 103, 227, 19, 64, 221, 28, 183, 21, 126, 51, 179, 38, 45, 219, 230, 177, 214, 204, 96, 96, 13, 121, 192, 237, 63, 134, 232, 220, 210, 145, 61, 145, 101, 159, 95, 224, 192, 211, 6, 17, 133 },
                            PasswordSalt = new byte[] { 90, 225, 51, 222, 186, 204, 140, 229, 222, 216, 2, 42, 23, 219, 44, 195, 153, 226, 172, 187, 200, 18, 82, 161, 46, 83, 117, 242, 77, 232, 120, 215, 1, 171, 227, 195, 70, 11, 34, 13, 114, 81, 144, 150, 82, 170, 74, 224, 120, 9, 255, 174, 199, 215, 71, 3, 217, 30, 255, 198, 172, 62, 127, 69, 41, 36, 40, 14, 173, 239, 240, 84, 131, 218, 120, 8, 172, 108, 134, 80, 123, 161, 188, 94, 179, 207, 112, 244, 190, 181, 227, 55, 185, 13, 152, 217, 120, 227, 42, 63, 70, 224, 181, 88, 83, 59, 141, 16, 137, 102, 237, 78, 143, 9, 38, 204, 129, 196, 111, 139, 127, 16, 184, 74, 140, 2, 119, 133 },
                            Role = 2,
                            Username = "seedUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
