// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stratoapi.Data;

#nullable disable

namespace stratoapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108125928_AddSoftDeletion")]
    partial class AddSoftDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("stratoapi.Models.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrometheusIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("MetricTypes");
                });

            modelBuilder.Entity("stratoapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seed@example.com",
                            IsDeleted = false,
                            PasswordHash = new byte[] { 229, 151, 129, 199, 101, 184, 113, 85, 185, 231, 201, 87, 208, 114, 108, 201, 98, 43, 78, 231, 189, 186, 182, 97, 214, 6, 123, 7, 104, 45, 204, 26, 141, 149, 17, 208, 255, 42, 193, 45, 59, 62, 62, 7, 145, 240, 127, 222, 185, 144, 104, 119, 166, 254, 108, 146, 137, 207, 104, 91, 5, 133, 145, 128 },
                            PasswordSalt = new byte[] { 225, 103, 2, 229, 130, 229, 139, 22, 55, 11, 180, 111, 251, 7, 12, 66, 179, 3, 254, 97, 126, 226, 136, 59, 31, 103, 49, 218, 195, 25, 118, 110, 98, 112, 135, 20, 115, 185, 251, 252, 105, 119, 74, 197, 202, 111, 193, 7, 170, 9, 19, 72, 212, 182, 186, 57, 14, 233, 248, 113, 160, 17, 166, 204, 2, 236, 253, 187, 60, 2, 164, 202, 175, 6, 207, 141, 164, 158, 12, 146, 70, 41, 195, 123, 87, 96, 144, 198, 64, 146, 250, 146, 10, 148, 239, 198, 240, 99, 52, 222, 17, 79, 104, 84, 167, 172, 73, 204, 14, 130, 127, 109, 135, 220, 173, 223, 206, 254, 115, 79, 130, 97, 161, 64, 13, 89, 225, 150 },
                            Role = 2,
                            Username = "seedUser"
                        });
                });

            modelBuilder.Entity("stratoapi.Models.MetricType", b =>
                {
                    b.HasOne("stratoapi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("stratoapi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
