// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stratoapi.Data;

#nullable disable

namespace stratoapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108122232_Metrics")]
    partial class Metrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("stratoapi.Models.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrometheusIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MetricTypes");
                });

            modelBuilder.Entity("stratoapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seed@example.com",
                            PasswordHash = new byte[] { 1, 245, 150, 104, 218, 18, 191, 109, 215, 131, 79, 254, 147, 19, 237, 82, 42, 170, 174, 161, 108, 35, 233, 35, 9, 159, 45, 37, 130, 136, 54, 221, 207, 69, 59, 37, 204, 38, 164, 247, 153, 174, 134, 135, 53, 220, 214, 19, 92, 52, 46, 82, 76, 163, 220, 91, 134, 75, 213, 27, 44, 174, 250, 51 },
                            PasswordSalt = new byte[] { 241, 164, 169, 122, 220, 136, 201, 206, 242, 107, 168, 34, 191, 37, 52, 246, 34, 20, 183, 147, 105, 190, 95, 99, 107, 198, 189, 93, 105, 184, 170, 246, 81, 32, 168, 65, 148, 51, 154, 233, 83, 127, 105, 168, 154, 173, 33, 147, 5, 116, 93, 121, 15, 90, 98, 179, 63, 230, 140, 29, 6, 46, 102, 145, 100, 214, 239, 8, 34, 62, 225, 198, 194, 48, 211, 146, 104, 153, 128, 237, 8, 212, 132, 226, 86, 92, 41, 253, 34, 141, 87, 178, 245, 179, 78, 81, 154, 150, 134, 177, 202, 239, 9, 88, 142, 224, 160, 193, 86, 212, 45, 47, 132, 60, 35, 9, 44, 253, 211, 152, 53, 243, 231, 44, 156, 232, 243, 79 },
                            Role = 2,
                            Username = "seedUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
